# helm chart repository.
repo: "https://concourse-charts.storage.googleapis.com"

# helm chart name.
chart: "concourse"

# helm chart version.
version: 17.0.12

# helm install values.
values: |-
  concourse:
    web:
      auth:
        mainTeam:
          oidc:
            group: admins
        oidc:
          enabled: false
          displayName: sso
          {{- if eq .sso "authentik"}}
          issuer: "{{- if eq .tls true -}}https{{- else -}}http{{- end -}}://authentik.{{ .domain }}:{{ .ingressPort }}/application/o/concourse"
          {{- end }}
      externalUrl: "{{- if eq .tls true -}}https{{- else -}}http{{- end -}}://concourse.{{ .domain }}:{{ .ingressPort }}"
      kubernetes:
        namespacePrefix: workflow-
        keepNamespace: false
  web:
    ingress:
      enabled: true
      hosts:
      - concourse.{{ .domain }}
  worker:
    env:
    - name: CONCOURSE_GARDEN_ALLOW_HOST_ACCESS
      value: "true"
  fullnameOverride: concourse
  postgresql:
    fullnameOverride: concourse-postgresql
  secrets:
    create: false

# helm hooks.
hooks: []
