# helm chart repository.
repo: "https://concourse-charts.storage.googleapis.com"

# helm chart name.
chart: "concourse"

# helm chart version.
version: 16.1.22

# helm install values.
values: 
  concourse:
    web:
      localAuth:
        enabled: true
      auth:
        mainTeam:
          localUser: "{{ .username }}"
      externalUrl: "{{ .domain }}"
  secrets:
    localUsers: "{{ .username }}:{{ .password | bcrypt }}"
  worker:
    env:
    - name: CONCOURSE_GARDEN_ALLOW_HOST_ACCESS
      value: "true"
    sidecarContainers:
    - name: buildkit-rootless
      image: moby/buildkit:rootless
      securityContext:
        privileged: true

# helm hooks.
hooks: []

# helm values parameters.
parameters:
- name: domain
- name: username
  default: trustacks
- name: password
  mask: true