# helm chart repository.
repo: "https://concourse-charts.storage.googleapis.com"

# helm chart name.
chart: "concourse"

# helm chart version.
version: 17.0.12

# helm install values.
values: |-
  concourse:
    web:
      localAuth:
        enabled: true
      auth:
        mainTeam:
          localUser: trustacks
          oidc:
            group: admins
        oidc:
          enabled: true
          displayName: sso
          {{- if eq .sso "authentik"}}
          issuer: "{{- if eq .tls true -}}https{{- else -}}http{{- end -}}://authentik.{{ .domain }}:{{ .ingressPort }}/application/o/concourse/"
          {{- end }}
          userNameKey: preferred_username
      externalUrl: "{{- if eq .tls true -}}https{{- else -}}http{{- end -}}://concourse.{{ .domain }}:{{ .ingressPort }}"
      kubernetes:
        namespacePrefix: trustacks-application-
        keepNamespace: false
  web:
    {{- if eq .network "private" }}
    sidecarContainers:                                                                                                                                                                         
    - name: auth-proxy                                                                                                                                                                           
      image: quay.io/trustacks/local-gd-proxy                                                                                                                                                    
      env:                                                                                                                                                                                       
      - name: UPSTREAM
        {{- if eq .sso "authentik"}}                                                                                                                                                                             
        value: authentik
        {{- end }}
      - name: LISTEN_PORT
        value: "{{ .ingressPort }}"
      - name: SERVICE
        {{- if eq .sso "authentik"}} 
        value: authentik 
        {{- end }}
    {{- end }}
    ingress:
      enabled: true
      hosts:
      - concourse.{{ .domain }}
      {{- if eq .network "public" }}
      annotations:
        cert-manager.io/cluster-issuer: {{ .certManagerClusterIssuer }}
    	  {{- if .ingressClass }}
        kubernetes.io/ingress.class: {{ .ingressClass }}
        {{- end }}
      tls:
      - hosts:
        - argo-cd.{{ .domain }}
        secretName: concourse-ingress-tls-cert
      {{- end }}
  worker:
    env:
    - name: CONCOURSE_GARDEN_ALLOW_HOST_ACCESS
      value: "true"
  fullnameOverride: concourse
  postgresql:
    fullnameOverride: concourse-postgresql
  secrets:
    create: false

# helm hooks.
hooks: []
