# helm chart repository.
repo: "https://concourse-charts.storage.googleapis.com"

# helm chart name.
chart: "concourse"

# helm chart version.
version: 17.0.12

# helm install values.
values: |-
  concourse:
    web:
      localAuth:
        enabled: true
      auth:
        mainTeam:
          localUser: {{ .username }}
  {{- if eq .tls true }}
      externalUrl: "https://concourse.{{ .domain }}:{{ .ingressPort }}"
  {{- else}}
      externalUrl: "http://concourse.{{ .domain }}:{{ .ingressPort }}"
  {{- end}}
      kubernetes:
        namespacePrefix: workflow-
        keepNamespace: false
  web:
    ingress:
      enabled: true
      hosts:
      - concourse.{{ .domain }}
  secrets:
    localUsers: "{{ .username }}:{{ .password | bcrypt }}"
  worker:
    env:
    - name: CONCOURSE_GARDEN_ALLOW_HOST_ACCESS
      value: "true"
  fullnameOverride: concourse
  postgresql:
    fullnameOverride: concourse-postgresql

# helm hooks.
hooks: []
