# helm chart repository.
repo: "https://github.com/bitnami-labs/sealed-secrets/releases/download/helm-v2.2.0"

# helm chart name.
chart: sealed-secrets

# helm chart version.
version: 2.2.0

# helm install values.
values: |-

# helm hooks.
hooks: []
