# helm chart repository.
repo: "https://github.com/goauthentik/helm/releases/download/authentik-2022.7.2/"

# helm chart name.
chart: "authentik"

# helm chart version.
version: 2022.7.2

# helm install values.
values: |-
  {{- $postgresqlPassword := randAlphaNum 32 -}}
  authentik:
  secret_key: {{ randAlphaNum 32 }}
  postgresql:
    password: {{ $postgresqlPassword }}
  ingress:
    enabled: true
    hosts:
    - host: authentik.{{ .domain }}
    paths:
    - path: "/"
      pathType: "Prefix"
  postgresql:
    enabled: true
    postgresqlPassword: {{ $postgresqlPassword }}
  redis:
    enabled: true
  envValueFrom:
    AUTHENTIK_BOOTSTRAP_TOKEN:
    secretKeyRef:
      name: authentik-bootstrap
      key: api-token

# helm hooks.
hooks: [
  "pre-install",
  "post-install"
]
