---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: authentik-hook-rbac
  annotations:
    "helm.sh/hook": pre-install,post-install
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "1"
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: authentik-hook-rbac
  annotations:
    "helm.sh/hook": pre-install,post-install
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "1"
subjects:
- kind: ServiceAccount
  name: authentik-hook-rbac
roleRef:
  kind: Role
  name: authentik-hook-rbac
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: authentik-hook-rbac
  annotations:
    "helm.sh/hook": pre-install,post-install
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "1"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: authentik-pre-install
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "2"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: pre-install
        image: {{ .image }}
        env:
        - name: CATALOG_MODE
          value: hook
        - name: HOOK_COMPONENT
          value: authentik
        - name: HOOK_KIND
          value: pre-install
      serviceAccount: authentik-hook-rbac
---
apiVersion: batch/v1
kind: Job
metadata:
  name: authentik-post-install
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "2"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: post-install
        image: {{ .image }}
        env:
        - name: CATALOG_MODE
          value: hook
        - name: HOOK_COMPONENT
          value: authentik
        - name: HOOK_KIND
          value: post-install
        - name: SERVICE_URL
          value: "{{`{{- if eq .tls true -}}https{{- else -}}http{{- end -}}://authentik`}}"
      serviceAccount: authentik-hook-rbac
