---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: authentik-hook-rbac
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: authentik-hook-rbac
subjects:
- kind: ServiceAccount
  name: authentik-hook-rbac
roleRef:
  kind: Role
  name: authentik-hook-rbac
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: authentik-hook-rbac
---
apiVersion: batch/v1
kind: Job
metadata:
  name: authentic-pre-install
  annotations:
    "helm.sh/hook": pre-install
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: pre-install
        image: quay.io/trustacks/catalog:latest
        env:
        - name: CATALOG_MODE
          value: hook
        - name: HOOK_COMPONENT
          value: authentik
        - name: HOOK_KIND
          value: pre-install
      serviceAccount: authentik-hook-rbac