---
apiVersion: v1
kind: Namespace
metadata:
  name: concourse-okteko-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: concourse-okteto-dev
  namespace: $NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: concourse-okteto-dev
  template:
    metadata:
      labels:
        app: concourse-okteto-dev
    spec:
      serviceAccount: $SERVICE_ACCOUNT
      containers:
      - image: busybox
        name: concourse-okteto-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: concourse-okteko-dev
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - patch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: concourse-okteko-dev
subjects:
- kind: ServiceAccount
  name: okteto-dev
  namespace: $NAMESPACE
roleRef:
  kind: Role
  name: okteto-dev
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: okteto-dev
  namespace: $NAMESPACE
