name: Build & Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: "Setup Go"
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      
      - name: Run Unit Test
        run: |
          sudo mkdir /data
          sudo ln -s /workspaces/catalog/pkg/components /data/components
          sudo ln -s /workspaces/catalog/pkg/catalog.yaml /data/config.yaml
          cd pkg && go test -v ./...
  
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: "Setup Go"
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          
      - name: Run Lint
        uses: golangci/golangci-lint-action@v3
    
  push_to_registry:
    name: Push the container image to Quay
    runs-on: ubuntu-latest
    needs: [unit_test, lint]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: quay.io/trustacks/catalog:latest
